import { NiamCardProps } from "@/components/niam-card";

export const NIAM_CARDS: NiamCardProps[] = [
  {
    title: "1",
    chinese: "玖丹迪得因夏巴扎玖巴央达 巴作比桑吉夏迦特巴拉 香擦洛",
    lines: [
      "Zom Dan Di",
      "Di Shen Shier Ba",
      "Za Zom Ba",
      "Yong Da Ber",
      "Zhor Ber Song Gee",
      "Shark Gia",
      "Ter Ba La",
      "Xiang Cher Lo",
    ],
  },
  {
    title: "2",
    chinese: "得因夏把 多吉酿波惹德將巴拉香擦洛",
    lines: [
      "Di Shen Shier Ba",
      "Dor Jee",
      "Syong Bo",
      "Rapp Der",
      "Jom Ba La",
      "Xiang Cher Lo",
    ],
  },
  {
    title: "3",
    chinese: "得因夏巴仁欽奧綽拉香擦洛",
    lines: ["Di Shen Shier Ba", "Ren Chen", "Om Chor La", "Xiang Cher Lo"],
  },
  {
    title: "4",
    chinese: "得因夏巴勤旺格嘉波拉 香檫洛",
    lines: ["Di Shen Shier Ba", "Sor Wang Ge", "Ger Bo La", "Xiang Cher Lo"],
  },
  {
    title: "5",
    chinese: "得因夏巴 華沃得拉委擦洛",
    lines: ["Di Shen Shier Ba", "Hua Wu", "Sdi La", "Xiang Cher Lo"],
  },
  {
    title: "6",
    chinese: "得因夏巴華华吉拉香擦洛",
    lines: ["Di Shen Shier Ba", "Huat Gee La", "Xiang Cher Lo"],
  },
  {
    title: "7",
    chinese: "得因夏巴 仁欽美拉 委擦洛",
    lines: ["Di Shen Shier Ba", "Ren Chen", "Mei La", "Xiang Cher Lo"],
  },
  {
    title: "8",
    chinese: "得因夏巴 仁欽達奧拉香擦洛",
    lines: ["Di Shen Shier Ba", "Ren Chen", "Da Oh La", "Xiang Cher Lo"],
  },
  {
    title: "9",
    chinese: "得因夏巴 通瓦敦友拉 香擦洛",
    lines: ["Di Shen Shier Ba", "Tong Waa", "Don Yo La", "Xiang Cher Lo"],
  },
  {
    title: "10",
    chinese: "得因夏巴 仁钦达瓦拉香擦洛",
    lines: ["Di Shen Shier Ba", "Ren Chen", "Dar Wa La", "Xiang Cher Lo"],
  },
  {
    title: "11",
    chinese: "得因夏巴 哲玛美巴拉 香擦洛",
    lines: ["Di Shen Shier Ba", "Zhe Ma", "Mei Ba La", "Xiang Cher Lo"],
  },
  {
    title: "12",
    chinese: "得因夏巴 华辛拉 香擦洛",
    lines: ["Di Shen Shier Ba", "Huar Jin La", "Xiang Cher Lo"],
  },
  {
    title: "13",
    chinese: "得因夏巴 倉巴拉 香擦洛",
    lines: ["Di Shen Shier Ba", "Chong Ba La", "Xiang Cher Lo"],
  },
  {
    title: "14",
    chinese: "得因夏巴 倉比辛 拉香擦洛",
    lines: ["Di Shen Shier Ba", "Chong Bee", "Shin La", "Xiang Cher Lo"],
  },
  {
    title: "15",
    chinese: "得因夏巴 切拉拉 香擦洛",
    lines: ["Di Shen Shier Ba", "Cher Ta La", "Xiang Cher Lo"],
  },
  {
    title: "16",
    chinese: "得因夏巴 切利拉拉 香擦洛",
    lines: ["Di Shen Shier Ba", "Cher Hee Ta La", "Xiang Cher Lo"],
  },
  {
    title: "17",
    chinese: "得因夏巴 华桑拉 香擦洛",
    lines: ["Di Shen Shier Ba", "Huar Song La", "Xiang Cher Lo"],
  },
  {
    title: "18",
    chinese: "得因夏巴 旃檀华拉 香擦洛",
    lines: ["Di Shen Shier Ba", "Zhan Za Bella", "Xiang Cher Lo"],
  },
  {
    title: "19",
    chinese: "得因夏巴 泽杰塔义拉 香擦洛",
    lines: ["Di Shen Shier Ba", "Zert Cert", "Ta Yee La", "Xiang Cher Lo"],
  },
  {
    title: "20",
    chinese: "得因夏巴 奥华拉 香擦洛",
    lines: ["Di Shen Shier Ba", "Wo Pek La", "Xiang Cher Lo"],
  },
  {
    title: "21",
    chinese: "得因夏巴 灭安美比华拉 香擦洛",
    lines: ["Di Shen Shier Ba", "Mia Ngat", "Mei Ber Hua La", "Xiang Cher Lo"],
  },
  {
    title: "22",
    chinese: "得因夏巴 这美杰沃拉 香擦洛",
    lines: ["Di Shen Shier Ba", "Zhe Mei Gear", "Verla", "Xiang Cher Lo"],
  },
  {
    title: "23",
    chinese: "得因夏巴 美多华拉 香擦洛",
    lines: ["Di Shen Shier Ba", "Mei Dok Hua La", "Xiang Cher Lo"],
  },
  {
    title: "24",
    chinese: "得因夏巴 倉比奥瑞 南巴钦巴拉 香擦洛",
    lines: [
      "Di Shen Shier Ba",
      "Chong Bee",
      "O Zer",
      "Nam Ber",
      "Ro Bee",
      "Ngom Ber",
      "Kent Ba La",
      "Xiang Cher Lo",
    ],
  },
  {
    title: "25",
    chinese: "得因夏巴 巴美奧瑞 南巴若維 溫巴欽巴拉 香擦洛",
    lines: [
      "Di Shen Shier Ba",
      "Bad Mee",
      "O Zer",
      "Nam Ber",
      "Ro Wee",
      "Ngon Ber",
      "Kent Ba La",
      "Xiang Cher Lo",
    ],
  },
  {
    title: "26",
    chinese: "得因夏巴 諾华拉 香擦洛",
    lines: ["Di Shen Shier Ba", "Nou Huar La", "Xiang Cher Lo"],
  },
  {
    title: "27",
    chinese: "得因夏巴 展比华拉 香 擦 洛",
    lines: ["Di Shen Shier Ba", "Zhen Bee", "Bella", "Xiang Cher Lo"],
  },
  {
    title: "28",
    chinese: "得因夏巴 参华辛德 永扎拉 香擦 洛",
    lines: [
      "Di Shen Shier Ba",
      "Chen Hual",
      "Hen Der",
      "Yong Za La",
      "Xiang Cher Lo",
    ],
  },
  {
    title: "29",
    chinese: "得因夏巴 旺波多格加灿杰嘉波拉 香擦洛",
    lines: [
      "Di Shen Shier Ba",
      "Wong Bu",
      "Dok Ger",
      "Game Chen Gear",
      "Ger Bo La",
      "Xiang Cher Lo",
    ],
  },
  {
    title: "30",
    chinese: "得因夏巴 辛德南巴浓比华拉 香擦洛",
    lines: [
      "Di Shen Shier Ba",
      "Hen Der",
      "Nam Ber",
      "Nong Ber",
      "Bella",
      "Xiang Cher Lo",
    ],
  },
  {
    title: "31",
    chinese: "得因夏巴 耶利辛德南巴嘉瓦拉 香 擦 洛",
    lines: [
      "Di Shen Shier Ba",
      "Yearly",
      "Hen Der",
      "Nam Ber",
      "Ger Waa La",
      "Xiang Cher Lo",
    ],
  },
  {
    title: "32",
    chinese: "得因夏巴 巴南巴浓巴协比华拉 香擦洛",
    lines: [
      "Di Shen Shier Ba",
      "Nam Ber",
      "Nong Bee",
      "Shark Ber",
      "Bella",
      "Xiang Cher Lo",
    ],
  },
  {
    title: "33",
    chinese: "得因夏巴 根內囊瓦果比华拉 香 擦 洛",
    lines: [
      "Di Shen Shier Ba",
      "Gen Nee",
      "Snong Waa",
      "Guo Ber",
      "Bella",
      "Xiang Cher Lo",
    ],
  },
  {
    title: "34",
    chinese: "得因夏巴 仁欽巴莫南巴浓巴拉 香 擦 洛",
    lines: [
      "Di Shen Shier Ba",
      "Ren Chen",
      "Bet Moo",
      "Nam Ber",
      "Non Ba La",
      "Xiang Cher Lo",
    ],
  },
  {
    title: "35",
    chinese:
      "得因夏巴 扎炯巴央達巴 作比桑吉 仁波切 当巴美拉 惹德耶巴 热旺嘉波拉 香擦洛",
    lines: [
      "Di Shen Shier Ba",
      "Za Zom Ba",
      "Yong Dar Ber",
      "Zhor Ber Song Gee",
      "Renpochi Dong",
      "Padmala",
      "Ratt Der",
      "Zhirt Ba",
      "Raw Wang Ger",
      "Ger Bo La",
      "Xiang Cher Lo",
    ],
  },
];
